apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 469331982253.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 469331982253.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e877e26b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
